name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  godot:
    name: Validate Godot project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.7.2
          use-dotnet: false

      - name: Check Godot version
        run: godot --version

      - name: Import project
        run: godot --headless --editor --quit

      - name: Validate project
        run: godot --headless --path . --editor --quit